import 'package:flutter_test/flutter_test.dart';
import 'package:fushi/src/media/video/url_stream_video.dart';
import 'package:youtube_explode_dart/youtube_explode_dart.dart' as yt;
import 'package:fushi/src/media/video/youtube_source_resolver.dart';
import 'package:fushi_audio/fushi_audio.dart' show AudioCue;

void main() {
  group('isYoutubeUrl', () {
    test('accepts watch and youtu.be', () {
      expect(isYoutubeUrl('https://www.youtube.com/watch?v=abc123'), true);
      expect(isYoutubeUrl('https://youtu.be/abc123'), true);
    });
    test('rejects non-youtube', () {
      expect(isYoutubeUrl('https://www.netflix.com/watch/1'), false);
      expect(isYoutubeUrl('/local/file.mp4'), false);
    });
  });

  group('parseYoutubeTimedTextToCues', () {
    test('converts timedtext XML to cues with ms bounds', () {
      const xml = '<transcript>'
          '<text start="1.5" dur="2.0">走り出した</text>'
          '<text start="4.0" dur="1.5">こんにちは</text>'
          '</transcript>';
      final cues = parseYoutubeTimedTextToCues(content: xml, bookKey: 'yt:abc');
      expect(cues.length, 2);
      expect(cues[0].text, '走り出した');
      expect(cues[0].startMs, 1500);
      expect(cues[0].endMs, 3500);
      expect(cues[1].startMs, 4000);
      expect(cues[1].endMs, 5500);
    });
    test('decodes entities and skips empty', () {
      const xml =
          '<transcript><text start="0" dur="1">&#39;</text><text start="1" dur="1"></text></transcript>';
      final cues = parseYoutubeTimedTextToCues(content: xml, bookKey: 'yt:x');
      expect(cues.length, 1);
      expect(cues[0].text, "'");
    });
  });

  // BUG-783：YouTube androidVr 现在一律返回 timedtext format="3" 的 <p t d>（毫秒），
  // 即使 fmt=srv1 也被无视；旧解析器只认 srv1 <text start dur>（秒）→ 0 cue → 字幕失效。
  // fixtures 用探测抓下来的真实结构（人工轨 <p>text</p>、ASR 轨 <p><s>词</s></p>）。
  group('parseYoutubeTimedTextToCues format 3 (BUG-783)', () {
    test('manual track: <p t d>text</p> 毫秒直用', () {
      const xml = '<?xml version="1.0" encoding="utf-8" ?>'
          '<timedtext format="3">\n<body>\n'
          '<p t="1360" d="1680">[♪♪♪]</p>\n'
          '<p t="18640" d="3240">♪ We&#39;re no strangers to love ♪</p>\n'
          '</body>\n</timedtext>';
      final cues = parseYoutubeTimedTextToCues(content: xml, bookKey: 'yt:abc');
      expect(cues.length, 2);
      expect(cues[0].text, '[♪♪♪]');
      expect(cues[0].startMs, 1360);
      expect(cues[0].endMs, 3040); // 1360 + 1680
      expect(cues[1].text, "♪ We're no strangers to love ♪");
      expect(cues[1].startMs, 18640);
      expect(cues[1].endMs, 21880); // 18640 + 3240
    });

    test('ASR track: 拼接 <s> 词级片段、跳空白滚动占位与 <w> 元素', () {
      const xml = '<?xml version="1.0" encoding="utf-8" ?>'
          '<timedtext format="3">\n'
          '<head>\n<ws id="0"/>\n<wp id="0"/>\n</head>\n<body>\n'
          '<w t="0" id="1" wp="1" ws="1"/>\n'
          '<p t="320" d="14260" w="1">[Music]</p>\n'
          '<p t="18790" w="1" a="1"> </p>\n'
          '<p t="18800" d="7160" w="1">'
          '<s ac="0">We&#39;re</s><s t="239" ac="0"> no</s>'
          '<s t="559" ac="0"> strangers</s><s t="1040" ac="0"> to</s></p>\n'
          '</body>\n</timedtext>';
      final cues = parseYoutubeTimedTextToCues(content: xml, bookKey: 'yt:asr');
      expect(cues.length, 2); // [Music] + 拼接行；空白 <p a="1"> 与 <w> 跳过
      expect(cues[0].text, '[Music]');
      expect(cues[0].startMs, 320);
      expect(cues[0].endMs, 14580);
      expect(cues[1].text, "We're no strangers to");
      expect(cues[1].startMs, 18800);
      expect(cues[1].endMs, 25960); // 18800 + 7160
    });

    test('format 3 无 d 属性时 endMs 退回 startMs（不崩）', () {
      const xml = '<timedtext format="3"><body>'
          '<p t="5000">末尾无时长</p>'
          '</body></timedtext>';
      final cues = parseYoutubeTimedTextToCues(content: xml, bookKey: 'yt:z');
      expect(cues.length, 1);
      expect(cues[0].startMs, 5000);
      expect(cues[0].endMs, 5000);
    });
  });

  // A（浏览器扩展→server 抓 YouTube 真字幕）：server 端点把抓到的轨 + cue 序列化成
  // 扩展可消费的 JSON。纯函数守卫其形状（扩展面板 cue 形状 {text,startMs,endMs}）。
  group('serializeYoutubeCaptionTracks (extension bridge)', () {
    YoutubeCaptionTrack track(String code, String name, bool auto) =>
        YoutubeCaptionTrack(
          baseUrl: 'https://x/timedtext?lang=$code',
          languageCode: code,
          languageName: name,
          isAutoGenerated: auto,
        );
    AudioCue cue(String text, int s, int e) => AudioCue()
      ..text = text
      ..startMs = s
      ..endMs = e;

    test('序列化轨元数据 + cue 三字段', () {
      final json = serializeYoutubeCaptionTracks(
        <YoutubeCaptionTrack>[track('ja', '日本語', false)],
        <List<AudioCue>>[
          <AudioCue>[cue('走り出した', 1500, 3500)],
        ],
      );
      final tracks = json['tracks'] as List<dynamic>;
      expect(tracks.length, 1);
      final t = tracks[0] as Map<String, dynamic>;
      expect(t['languageCode'], 'ja');
      expect(t['languageName'], '日本語');
      expect(t['isAutoGenerated'], false);
      expect(t['isTranslated'], false);
      final cues = t['cues'] as List<dynamic>;
      expect(cues.length, 1);
      expect(cues[0], <String, dynamic>{
        'text': '走り出した',
        'startMs': 1500,
        'endMs': 3500,
      });
    });

    test('cue 为空的轨被剔除（下载失败不占面板一格）', () {
      final json = serializeYoutubeCaptionTracks(
        <YoutubeCaptionTrack>[
          track('ja', '日本語', false),
          track('en', 'English', true),
        ],
        <List<AudioCue>>[
          <AudioCue>[cue('あ', 0, 1000)],
          <AudioCue>[], // en 轨下载失败/空
        ],
      );
      final tracks = json['tracks'] as List<dynamic>;
      expect(tracks.length, 1);
      expect((tracks[0] as Map<String, dynamic>)['languageCode'], 'ja');
    });
  });

  // TODO-1159 M0：导入对话框「网页地址」软警告的判定谓词——命中已知网页视频站
  // 且不是 YouTube 时才警告（YouTube 已由 resolveYoutubeSource 支持解析）。这里断言
  // 该组合谓词的真值表，守卫 YouTube 抑制 / 非 YouTube 保留不被回退。
  group('webpage warning suppression predicate (TODO-1159 M0)', () {
    bool warns(String url) => isKnownWebPageVideoUrl(url) && !isYoutubeUrl(url);
    test('YouTube 各形态一律不警告', () {
      expect(warns('https://www.youtube.com/watch?v=abc123'), isFalse);
      expect(warns('https://youtu.be/abc123'), isFalse);
      expect(warns('https://m.youtube.com/watch?v=abc'), isFalse);
      expect(warns('https://music.youtube.com/watch?v=abc'), isFalse);
      expect(warns('https://www.youtube-nocookie.com/embed/abc'), isFalse);
    });
    test('非 YouTube 网页视频站仍保留警告', () {
      expect(warns('https://www.netflix.com/watch/1'), isTrue);
      expect(warns('https://www.bilibili.com/video/BV1'), isTrue);
      expect(warns('https://www.nicovideo.jp/watch/sm1'), isTrue);
    });
    test('普通直链不警告', () {
      expect(warns('https://cdn.example.com/a.m3u8'), isFalse);
      expect(warns('https://example.com/video.mp4'), isFalse);
    });
  });

  // TODO-1307 A1：多 client 兜底顺序——androidVr 首选（零回归），失败才回落 ios、tv。
  group('A1 多 client 兜底顺序 (TODO-1307)', () {
    test('kYoutubeManifestClientFallback = androidVr -> ios -> tv', () {
      expect(kYoutubeManifestClientFallback.length, 3);
      expect(
        identical(
            kYoutubeManifestClientFallback[0], yt.YoutubeApiClient.androidVr),
        isTrue,
        reason: 'androidVr 必须首选（其直链无需签名解密、libmpv 普通 UA 可拉取）',
      );
      expect(
        identical(kYoutubeManifestClientFallback[1], yt.YoutubeApiClient.ios),
        isTrue,
      );
      expect(
        identical(kYoutubeManifestClientFallback[2], yt.YoutubeApiClient.tv),
        isTrue,
      );
    });
  });

  // TODO-1307 字幕后置入口：best-effort，无法解析出 videoId 时返回空 cue，绝不抛/阻断播放。
  group('resolveYoutubeCaptions best-effort (TODO-1307)', () {
    test('无法解析的 URL -> 空 cue、不联网、不抛', () async {
      expect(await resolveYoutubeCaptions('not a youtube url'), isEmpty);
      expect(await resolveYoutubeCaptions(''), isEmpty);
    });
  });
}
