// BUG-1289：YouTube 字幕轨标签退化成语言码 + 人工/ASR 重名，用户「不知道该选哪条」。
//
// 这里钉住的是**轨的呈现**，不是 cue 解析（cue 侧另有 youtube_source_resolver_test.dart）。
// 用例数据取自真实抓包：androidVr innertube player response 对 `dQw4w9WgXcQ` 返回 6 条轨，
// `name.simpleText` **全部缺失**，故 [YoutubeCaptionTrack.languageName] 一律是语言码兜底值。
import 'package:flutter_test/flutter_test.dart';
import 'package:fushi/src/media/video/youtube_source_resolver.dart';

/// 实测轨表（languageName 全部退化成 languageCode，= `t.languageName ?? t.languageCode` 的结果）。
/// 注意其中**两条都是 `en`**，一条人工一条 ASR —— 原 bug 下这两行标签完全相同。
List<YoutubeCaptionTrack> _realWorldTracks() => <YoutubeCaptionTrack>[
      _track('en', autoGenerated: false),
      _track('en', autoGenerated: true),
      _track('de-DE', autoGenerated: false),
      _track('ja', autoGenerated: false),
      _track('pt-BR', autoGenerated: false),
      _track('es-419', autoGenerated: false),
    ];

YoutubeCaptionTrack _track(
  String code, {
  required bool autoGenerated,
  String? name,
  String? translateTo,
}) =>
    YoutubeCaptionTrack(
      baseUrl: 'https://www.youtube.com/api/timedtext?v=dQw4w9WgXcQ&lang=$code',
      languageCode: code,
      // 生产里由 `t.languageName ?? t.languageCode` 产生：YouTube 没给名字时就是语言码本身。
      languageName: name ?? code,
      isAutoGenerated: autoGenerated,
      translateToCode: translateTo,
    );

/// 测试用的 i18n 假件（与真实文案同形，避免把断言绑死在某语言的具体译文上）。
String _translated(String lang) => '$lang (translated)';
String _autoGenerated(String lang) => '$lang (auto-generated)';

String _label(YoutubeCaptionTrack t) => youtubeCaptionTrackLabel(
      t,
      translated: _translated,
      autoGenerated: _autoGenerated,
    );

void main() {
  group('youtubeCaptionLanguageLabel：语言名不再是裸机器码', () {
    test('表内主码给出母语写法', () {
      expect(youtubeCaptionLanguageLabel(_track('ja', autoGenerated: false)),
          '日本語');
      expect(youtubeCaptionLanguageLabel(_track('en', autoGenerated: false)),
          'English');
      expect(youtubeCaptionLanguageLabel(_track('ko', autoGenerated: false)),
          '한국어');
    });

    test('地区子码括注保留（pt-BR / es-419 是实测真实出现的轨）', () {
      expect(youtubeCaptionLanguageLabel(_track('pt-BR', autoGenerated: false)),
          'Português (BR)');
      expect(
          youtubeCaptionLanguageLabel(_track('es-419', autoGenerated: false)),
          'Español (419)');
      expect(youtubeCaptionLanguageLabel(_track('de-DE', autoGenerated: false)),
          'Deutsch (DE)');
    });

    test('表外语言回退原码大写，不崩不留空', () {
      expect(
          youtubeCaptionLanguageLabel(_track('gsw-CH', autoGenerated: false)),
          'GSW (CH)');
      expect(youtubeCaptionLanguageLabel(_track('xx', autoGenerated: false)),
          'XX');
    });

    test('YouTube 真给了本地化名时优先用它（换 client 后自动受益，不被查表覆盖）', () {
      expect(
        youtubeCaptionLanguageLabel(
            _track('ja', autoGenerated: false, name: '日本語 (自動生成)')),
        '日本語 (自動生成)',
      );
    });
  });

  group('youtubeCaptionTrackLabel：轨与轨必须可分辨', () {
    test('同语言的人工轨与 ASR 轨标签不同（原 bug：两行都是 en）', () {
      final YoutubeCaptionTrack human = _track('en', autoGenerated: false);
      final YoutubeCaptionTrack asr = _track('en', autoGenerated: true);
      expect(_label(human), isNot(equals(_label(asr))));
      expect(_label(human), 'English');
      expect(_label(asr), 'English (auto-generated)');
    });

    test('实测 6 条轨两两标签互异，且都不是裸语言码', () {
      final List<YoutubeCaptionTrack> tracks = _realWorldTracks();
      final List<String> labels =
          tracks.map<String>(_label).toList(growable: false);

      // 核心不变式：不同 trackKey 的轨，标签必须不同（否则列表里出现无法区分的重复行）。
      expect(labels.toSet().length, labels.length, reason: '标签有重复：$labels');
      expect(tracks.map((YoutubeCaptionTrack t) => t.trackKey).toSet().length,
          tracks.length);

      // 且不能再退化成机器码本身。
      for (int i = 0; i < tracks.length; i++) {
        expect(labels[i], isNot(equals(tracks[i].languageCode)),
            reason: '第 $i 条仍显示为裸语言码');
      }
    });

    test('翻译变体与其源轨标签不同（母语对照不撞车）', () {
      final YoutubeCaptionTrack source = _track('ja', autoGenerated: false);
      final YoutubeCaptionTrack tl = source.translatedTo('zh');
      expect(_label(tl), isNot(equals(_label(source))));
      expect(_label(tl), '日本語 (translated)');
    });

    test('翻译标注优先于 ASR 标注（一条轨只挂一个标注，不叠成长串）', () {
      final YoutubeCaptionTrack asrTranslated =
          _track('en', autoGenerated: true).translatedTo('zh');
      expect(_label(asrTranslated), 'English (translated)');
    });
  });
}
