// AUTO-GENERATED by tool/native_gen/gen_kanji_standardization.py — DO NOT EDIT.
// Source: yomidevs/kanji-processor (MIT, pin 452cc2db) src/full_list.json.
// Maps 異体字 (variant) -> 親字 (parent), per upstream README "Convert 異体字 to 親字".
// LICENSE for the data lives alongside: KANJI_STANDARDIZATION_LICENSE.
#pragma once

#include <cstddef>

namespace kanji_standardization {

struct VariantToParent {
  char32_t variant;
  char32_t parent;
};

// Flat, code-point-sorted variant->parent table.
extern const VariantToParent kVariantToParent[];
extern const std::size_t kVariantToParentCount;

}  // namespace kanji_standardization
