// 重建 fushi/assets/lnreader/lnreader_libs.js：
//   cd tool/lnreader && npm ci && npm run build
// 产物入库（运行时不需要 node），版本钉在 package.json / package-lock.json。
import { build } from 'esbuild';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const here = path.dirname(fileURLToPath(import.meta.url));
await build({
  entryPoints: [path.join(here, 'libs_entry.js')],
  outfile: path.join(
    here,
    '..',
    '..',
    'fushi',
    'assets',
    'lnreader',
    'lnreader_libs.js',
  ),
  bundle: true,
  minify: true,
  format: 'iife',
  platform: 'browser',
  target: ['chrome90', 'safari15'],
  legalComments: 'eof',
  banner: {
    js: '/* Generated by tool/lnreader/build_libs.mjs — do not edit. cheerio (MIT), htmlparser2 (MIT), dayjs (MIT), protobufjs (BSD-3-Clause), @noble/ciphers (MIT). */',
  },
});
