import fs from 'node:fs';
import path from 'node:path';
import process from 'node:process';
import {fileURLToPath} from 'node:url';

const repositoryRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const sourceRoot = path.join(
  repositoryRoot,
  'fushi',
  'assets',
  'popup',
  'yomitan-26.6.15',
);
const entryPath = path.join(sourceRoot, 'fushi-glossary-adapter.js');
const styleDataPath = path.join(sourceRoot, 'data', 'structured-content-style.json');
const outputPaths = [
  path.join(repositoryRoot, 'fushi', 'assets', 'popup', 'yomitan-glossary-renderer.js'),
  path.join(
    repositoryRoot,
    'fushi',
    'assets',
    'browser_extension',
    'vendor',
    'yomitan-glossary-renderer.js',
  ),
  path.join(
    repositoryRoot,
    'tools',
    'browser-extension',
    'vendor',
    'yomitan-glossary-renderer.js',
  ),
];

const importPattern = /^\s*import\s+[\s\S]*?\s+from\s+['"]([^'"]+)['"];\s*/gm;
const visited = new Set();
const orderedModules = [];

function visit(modulePath) {
  modulePath = path.resolve(modulePath);
  if (visited.has(modulePath)) {
    return;
  }
  visited.add(modulePath);
  const source = fs.readFileSync(modulePath, 'utf8');
  for (const match of source.matchAll(importPattern)) {
    const specifier = match[1];
    if (!specifier.startsWith('.')) {
      throw new Error(`Unsupported external import ${specifier} in ${modulePath}`);
    }
    visit(path.resolve(path.dirname(modulePath), specifier));
  }
  orderedModules.push({modulePath, source});
}

function convertModuleToClassicScript(source) {
  return source
    .replace(importPattern, '')
    .replace(
      /^(\s*)export\s+(async\s+)?(class|function|const|let|var)\s+/gm,
      '$1$2$3 ',
    )
    .replace(/^\s*export\s*\{[\s\S]*?\};?\s*$/gm, '');
}

visit(entryPath);

const styleData = JSON.parse(fs.readFileSync(styleDataPath, 'utf8'));
const modules = orderedModules.map(({modulePath, source}) => {
  const relative = path.relative(repositoryRoot, modulePath).replaceAll('\\', '/');
  return `\n// ---- ${relative} ----\n${convertModuleToClassicScript(source)}`;
}).join('\n');

const bundle = `/*
 * Generated by tool/build_yomitan_glossary_renderer.mjs.
 * Do not edit this file directly.
 *
 * Contains unminified GPL-3.0-or-later Yomitan 26.6.15 source. Individual
 * upstream copyright/license headers are retained below. See
 * assets/popup/yomitan-26.6.15/NOTICE.md.
 */
(function (global) {
'use strict';
${modules}

const __fushiYomitanGlossaryRenderer = new FushiYomitanGlossaryRenderer(
    global.document,
    global.window || global,
    ${JSON.stringify(styleData)},
);
global.__fushiYomitanGlossaryRenderer = __fushiYomitanGlossaryRenderer;
if (global.window && global.window !== global) {
    global.window.__fushiYomitanGlossaryRenderer = __fushiYomitanGlossaryRenderer;
}
})(globalThis);
`;

for (const outputPath of outputPaths) {
  fs.mkdirSync(path.dirname(outputPath), {recursive: true});
  fs.writeFileSync(outputPath, bundle, 'utf8');
}

console.log(
  `Built ${outputPaths.length} Yomitan glossary renderer mirrors ` +
  `from ${orderedModules.length} modules (${Buffer.byteLength(bundle)} bytes each).`,
);
