#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Offline generator: kanji-processor full_list.json -> kanji_standardization_data.{h,cpp}

One-shot vendoring tool. NOT part of the CMake build — the generated .h/.cpp are
checked into native/fushidicts/fushidicts_src/text_processor/ as ordinary sources
and compiled like any other file. Re-run only when bumping the upstream pin.

Source data: yomidevs/kanji-processor (MIT), pin 452cc2db, file src/full_list.json.
Direction (per its README): "Convert 異体字 to 親字" — each entry has one `oyaji`
(親字 / parent) and a list of `itaiji` (異体字 / variants). We emit the flat
variant->parent map exactly as upstream's standardize_kanji() builds at runtime,
but precomputed so the runtime does zero JSON parsing.

Usage:
  python tool/native_gen/gen_kanji_standardization.py \
      <path/to/full_list.json> <path/to/output_dir>
"""
from __future__ import annotations

import json
import sys
from pathlib import Path


def codepoint(s: str) -> int:
    """Return the single Unicode code point of a 1-char string (by code point,
    not UTF-16 unit), matching upstream's utf8::utf8to32(...).front()."""
    cps = [ord(c) for c in s]
    if len(cps) != 1:
        raise ValueError(f"expected exactly one code point, got {len(cps)}: {s!r}")
    return cps[0]


def main(argv: list[str]) -> int:
    if len(argv) != 3:
        print(__doc__)
        return 2

    src_json = Path(argv[1])
    out_dir = Path(argv[2])
    out_dir.mkdir(parents=True, exist_ok=True)

    data = json.loads(src_json.read_text(encoding="utf-8"))

    # Build variant(itaiji) -> parent(oyaji), deterministic order by variant code point.
    # Last-writer-wins on collision mirrors upstream's map assignment; we additionally
    # sort so the generated file is reproducible across runs/machines.
    mapping: dict[int, int] = {}
    collisions: list[tuple[int, int, int]] = []
    for entry in data:
        parent = codepoint(entry["oyaji"])
        for variant_str in entry["itaiji"]:
            variant = codepoint(variant_str)
            if variant in mapping and mapping[variant] != parent:
                collisions.append((variant, mapping[variant], parent))
            mapping[variant] = parent

    pairs = sorted(mapping.items())

    header = out_dir / "kanji_standardization_data.h"
    source = out_dir / "kanji_standardization_data.cpp"

    h_lines = [
        "// AUTO-GENERATED by tool/native_gen/gen_kanji_standardization.py — DO NOT EDIT.",
        "// Source: yomidevs/kanji-processor (MIT, pin 452cc2db) src/full_list.json.",
        "// Maps 異体字 (variant) -> 親字 (parent), per upstream README \"Convert 異体字 to 親字\".",
        "// LICENSE for the data lives alongside: KANJI_STANDARDIZATION_LICENSE.",
        "#pragma once",
        "",
        "#include <cstddef>",
        "",
        "namespace kanji_standardization {",
        "",
        "struct VariantToParent {",
        "  char32_t variant;",
        "  char32_t parent;",
        "};",
        "",
        "// Flat, code-point-sorted variant->parent table.",
        "extern const VariantToParent kVariantToParent[];",
        "extern const std::size_t kVariantToParentCount;",
        "",
        "}  // namespace kanji_standardization",
        "",
    ]
    header.write_text("\n".join(h_lines), encoding="utf-8")

    c_lines = [
        "// AUTO-GENERATED by tool/native_gen/gen_kanji_standardization.py — DO NOT EDIT.",
        "// Source: yomidevs/kanji-processor (MIT, pin 452cc2db) src/full_list.json.",
        '#include "kanji_standardization_data.h"',
        "",
        "namespace kanji_standardization {",
        "",
        "const VariantToParent kVariantToParent[] = {",
    ]
    for variant, parent in pairs:
        c_lines.append(f"    {{0x{variant:04X}, 0x{parent:04X}}},")
    c_lines.append("};")
    c_lines.append("")
    c_lines.append(
        "const std::size_t kVariantToParentCount ="
    )
    c_lines.append(
        "    sizeof(kVariantToParent) / sizeof(kVariantToParent[0]);"
    )
    c_lines.append("")
    c_lines.append("}  // namespace kanji_standardization")
    c_lines.append("")
    source.write_text("\n".join(c_lines), encoding="utf-8")

    print(f"entries(json)={len(data)} mappings={len(pairs)} collisions={len(collisions)}")
    if collisions:
        for variant, old, new in collisions[:20]:
            print(f"  collision: U+{variant:04X} was U+{old:04X} now U+{new:04X}")
    print(f"wrote {header} ({header.stat().st_size} bytes)")
    print(f"wrote {source} ({source.stat().st_size} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
